# configs/box.yaml
placeholders:
  mass:               1.0
  ixx:                0.166667
  ixy:                0
  ixz:                0
  iyy:                0.166667
  iyz:                0
  izz:                0.166667
  scale:              "1 1 1"
  static:             0
  allow_auto_disable: 1

# this is the full SDF template for a mesh-based shape
template: |
  <?xml version='1.0'?>
  <sdf version='1.7'>
    <model name='{model_name}'>
      <link name='link_0'>
        <inertial>
          <mass>{mass}</mass>
          <inertia>
            <ixx>{ixx}</ixx><ixy>{ixy}</ixy><ixz>{ixz}</ixz>
            <iyy>{iyy}</iyy><iyz>{iyz}</iyz><izz>{izz}</izz>
          </inertia>
          <pose>0 0 0 0 -0 0</pose>
        </inertial>
        <pose>0 0 0 0 -0 0</pose>
        <gravity>1</gravity>
        <self_collide>0</self_collide>
        <kinematic>0</kinematic>
        <enable_wind>0</enable_wind>
        <visual name='visual'>
          <pose>0 0 0 0 -0 0</pose>
          <geometry>
            <mesh>
              <uri>model://{model_name}/meshes/{dae_filename}</uri>
              <scale>{scale}</scale>
            </mesh>
          </geometry>
          <material><shader type='pixel'><normal_map>__default__</normal_map></shader>
          <emissive>0 0 0 1</emissive></material>
          <transparency>0</transparency>
          <cast_shadows>1</cast_shadows>
        </visual>
        <collision name='collision'>
          <laser_retro>0</laser_retro><max_contacts>10</max_contacts>
          <pose>0 0 0 0 -0 0</pose>
          <geometry>
            <mesh>
              <uri>model://{model_name}/meshes/{dae_filename}</uri>
              <scale>{scale}</scale>
            </mesh>
          </geometry>
          <!-- surface/friction/bounce omitted for brevity -->
        </collision>
      </link>
      <static>{static}</static>
      <allow_auto_disable>{allow_auto_disable}</allow_auto_disable>
    </model>
  </sdf>
